services:
  - type: web
    name: petsitting
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn petsitting.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: petsitting-6lk4.onrender.com
      - key: SECRET_KEY
        generateValue: true
